#!/bin/bash

ZERO_DEV_OS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if ! [ -d "$ZERO_DEV_OS_DIR/nic-cli/.build" ]; then
  cd $ZERO_DEV_OS_DIR/nic-cli
  swift build
  cd -
fi

$ZERO_DEV_OS_DIR/nic-cli/.build/debug/nic-cli $*

echo ""
